apiVersion: rbac.authorization.k8s.io/v1
kind: Role
subjects:
- kind: Group
  name: api
  apiGroup: rbac.authorization.k8s.io
metadata:
  namespace: web
  name: web-reader-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs:
  - "get"
  - "list"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
subjects:
- kind: Group
  name: api
  apiGroup: rbac.authorization.k8s.io
metadata:
  namespace: api
  name: api-writer-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
