apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip
  labels:
    app: trip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trip
  template:
    metadata:
      labels:
        app: trip
    spec:
      containers:
      - name: trip
        image: registryyvc5218.azurecr.io/uehara/trip:latest
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
