apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: user-java
        image: registryyvc5218.azurecr.io/asami/poi
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlsetting
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlsetting
              key: password
        - name: SQL_SERVER
          value: "sqlserveryvc5218.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: user-java
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: user-java
